name: One

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v4
        with:
          repository: libgit2/libgit2
          path: libgit2
      - name: Build libgit2
        uses: threeal/cmake-action@main
        with:
          source-dir: libgit2
          build-dir: libgit2/build
      - name: Build luagit2
        run: |
          ls -la libgit2
          ls -la libgit2/build
          ls -la libgit2/build/include
          luarocks install https://raw.github.com/libgit2/luagit2/master/lua-git2-scm-0.rockspec GIT2_DIR=libgit2/build
          luarocks make
          
